# General Settings
logo: 
name: Mobcount
description: Counting with Video
site_owner_name: Jim Dallas
email: jimd@yantantethera
favicon: 
twitter_handler: 
analytics_code: 
disqus: 

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

# Modules Settings
show_tags: 0
show_email: 0
show_rss: 0
show_comments: 0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serving
url: "http://jimdytt.github.io"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 24
paginate_path: "/all/:num/"

# Conversion
markdown: kramdown

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed